apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: "ratelimit-httpbin" # domain別に設定が可能
    descriptors:
      - key: service-level
        value: "admin"
        rate_limit:
          unit: minute
          requests_per_unit: 10
      - key: header_match
        rate_limit:
          unit: minute
          requests_per_unit: 1


