apiVersion: v1
kind: Service
metadata:
  name: statsd
  labels:
    app: statsd
spec:
  ports:
  - name: statsd
    port: 9125
    targetPort: 9125
  - name: statsd-metrics
    port: 9102
    targetPort: 9102
  selector:
    app: statsd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd
  template:
    metadata:
      labels:
        app: statsd
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: statsd
        args: ["--statsd.mapping-config=/etc/statsd-exporter/conf.yaml"]
        image: prom/statsd-exporter:v0.18.0
        imagePullPolicy: Always
        ports:
        - name: statsd
          containerPort: 9125
        - name: statsd-metrics
          containerPort: 9102
        volumeMounts:
        - name: statsd-volume
          mountPath: /etc/statsd-exporter/conf.yaml
          subPath:   statsd.yaml
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: statsd-volume
        configMap:
          name: statsd-config
